# Generated by Django 5.2.5 on 2025-08-14 12:58

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=posts.models.image_upload_path)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('dong', models.CharField(blank=True, max_length=50)),
                ('location_detail', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
