# Generated by Django 5.2.5 on 2025-08-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_like_post_likes_count_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_likes_c_925000_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-likes_count', '-created_at'], name='posts_post_likes_c_86156e_idx'),
        ),
    ]
