# Generated by Django 5.2.5 on 2025-08-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_latitude_post_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='writer',
        ),
    ]
