# Generated by Django 5.2.5 on 2025-08-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_image_news_author_news_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='body',
            new_name='summary',
        ),
    ]
