# Generated by Django 5.2.5 on 2025-08-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_body_news_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short_title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
