# Generated by Django 5.2.5 on 2025-08-20 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=150)),
                ("description", models.TextField(blank=True)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["end_at"], name="surveys_sur_end_at_7bb19c_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SurveyOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50)),
                ("order_num", models.PositiveSmallIntegerField(default=0)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "ordering": ["order_num", "id"],
            },
        ),
        migrations.CreateModel(
            name="SurveyVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=40)),
                ("opinion_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="surveys.surveyoption",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="surveys.survey",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="surveyoption",
            index=models.Index(
                fields=["survey", "order_num"], name="surveys_sur_survey__a7ff11_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyvote",
            constraint=models.UniqueConstraint(
                fields=("survey", "session_key"),
                name="uniq_vote_per_session_per_survey",
            ),
        ),
    ]
