# Generated by Django 5.2.5 on 2025-08-21 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0002_agency_survey_agency_authcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="agency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="surveys",
                to="surveys.agency",
            ),
        ),
    ]
